# Site settings
title: collaborative design
email: oresmus@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    a blog about collaborative design of complex projects,
    and other things I find interesting
    (especially if they involve programming, math, or science).
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://oresmus.github.io" # the base hostname & protocol for your site
### twitter_username: jekyllrb
github_username:  oresmus

# Build settings
markdown: kramdown

# Post defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: "blog"
